name: Deploy Workflow

on:
  # Allows manual triggering of the workflow
  workflow_dispatch:

  # Optionally trigger on push to main if you want to run this automatically
  push:
    branches:
      - main

jobs:
  deploy_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Dev
        env:
          ENVIRONMENT: dev
        run: |
          # Deploy to your Dev environment (e.g., SSH, cloud CLI, etc.)
          echo "Deploying to Dev environment..."

  review_stage:
    name: Manual Approval for Stage Deployment
    runs-on: ubuntu-latest
    needs: deploy_dev
    steps:
      - name: Awaiting approval to deploy to Stage
        run: echo "Waiting for manual approval to deploy to Stage..."
      - name: Approval step
        uses: hmarr/approve-action@v2
        with:
          message: "Approve to deploy to Stage environment"

  deploy_stage:
    name: Deploy to Stage
    runs-on: ubuntu-latest
    needs: review_stage # Runs only if 'review_stage' succeeds

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Stage
        env:
          ENVIRONMENT: stage
        run: |
          # Deploy to your Stage environment
          echo "Deploying to Stage environment..."

  review_prod:
    name: Manual Approval for Prod Deployment
    runs-on: ubuntu-latest
    needs: deploy_stage
    steps:
      - name: Awaiting approval to deploy to Prod
        run: echo "Waiting for manual approval to deploy to Prod..."
      - name: Approval step
        uses: hmarr/approve-action@v2
        with:
          message: "Approve to deploy to Prod environment"

  deploy_prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: review_prod # Runs only if 'review_prod' succeeds

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Prod
        env:
          ENVIRONMENT: prod
        run: |
          # Deploy to your Prod environment
          echo "Deploying to Prod environment..."
