name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Dev
        env:
          ENVIRONMENT: dev
        run: |
          # Deploy to your Dev environment (e.g., SSH, cloud CLI, etc.)
          echo "Deploying to Dev environment..."

  deploy_stage:
    name: Deploy to Stage
    runs-on: ubuntu-latest
    needs: deploy_dev # Runs only if 'deploy_dev' succeeds

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Stage
        env:
          ENVIRONMENT: stage
        run: |
          # Deploy to your Stage environment
          echo "Deploying to Stage environment..."

  deploy_prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy_stage # Runs only if 'deploy_stage' succeeds

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Prod
        env:
          ENVIRONMENT: prod
        run: |
          # Deploy to your Prod environment
          echo "Deploying to Prod environment..."
