name: Deploy Workflow

on:
  # Allows manual triggering of the workflow
  workflow_dispatch:

  # Optionally trigger on push to main if you want to run this automatically
  push:
    branches:
      - main

jobs:
  manual_review:
    name: Manual Approval to Start Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Awaiting approval to start deployment
        run: echo "Waiting for manual approval to start deployment..."

      - name: Approval step
        uses: hmarr/approve-action@v2
        with:
          message: "Approve to start deployment process"

  deploy_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: manual_review # Runs only if 'manual_review' is approved

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to Dev
        env:
          ENVIRONMENT: dev
        run: |
          # Deploy to your Dev environment (e.g., SSH, cloud CLI, etc.)
          echo "Deploying to Dev environment..."

  deploy_stage:
    name: Deploy to Stage
    runs-on: ubuntu-latest
    needs: deploy_dev # Runs only if 'deploy_dev' succeeds

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to Stage
        env:
          ENVIRONMENT: stage
        run: |
          # Deploy to your Stage environment
          echo "Deploying to Stage environment..."

  deploy_prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy_stage # Runs only if 'deploy_stage' succeeds

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to Prod
        env:
          ENVIRONMENT: prod
        run: |
          # Deploy to your Prod environment
          echo "Deploying to Prod environment..."
